### PR TITLE
Add Titan X Maxwell benchmarks

### PR DESCRIPTION
**Pull request by tdeboissiere**
I have added some Titan X  Maxwell benchmarks.

A few observations:
- I have better caffe results (obtained by running `subprocess.call(CAFFE + " time -model vgg16_deploy.prototxt -iterations 100 -gpu 0", shell=True)` in your script). Any idea why ? I just compiled caffe from source today.
- I have better theano times (but then again, a more recent theano version).
- My theano times are better than my tensorflow times.
- I will try to upload a neon result ASAP but I am struggling with cuda version conflicts.

### CODE REVIEW

**Comment by aizvorski** [comment]
@tdeboissiere Very nice, thank you!  I'll do a couple of quick edits and merge this tomorrow.

The caffe results with `caffe time -model ...` are not valid, as I discovered :)  That does only forward+backward but not parameter update.  You really have to run it with `caffe train --solver ...` to have an apples to apples comparison with what the other frameworks are doing.  Could you please re-run that way?

It is possible that theano has something that makes it extra-slow on Pascal only.  I will upgrade my theano and rerun.  

Could you also include your results/*.output files in the pull request?  I wasn't really planning that far ahead, but should probably create directories under results/ for different hardware/configs/runs. I'll try to come up with some sensible scheme for that.

**Comment by tdeboissiere** [comment]
Sure, I'll run that tomorrow.

As far as the caffe benchmark is concerned, how did you time it in the end ?
Do you time the subprocess call and then average over 100 iterations ?

**Comment by tdeboissiere** [comment]
Now the caffe time is more reasonable. You may use/discard the parsing script as needed. Still working on neon...

**Comment by tdeboissiere** [comment]
Finally found a way to get neon working so all benchmarks are up to date !

For reference, the problem was with pip install pycuda which assumed that you had CUDA 7.5 instead of CUDA 8.0. I fixed this by installing from source.

**Comment by aizvorski** [comment]
Looks good, thanks!  I moved the results to a subdirectory and merged.

**Pull request merged**
